/**
* <html>
*  <body>
*   <P> Copyright 2017 阳光康众 </p>
*   <p> All rights reserved.</p>
*   <p> Created on 2017年7月9日</p>
*   <p> Created by Yuce</p>
*  </body>
* </html>
*/
package cn.ucaner.security.entity;

import cn.ucaner.framework.mvc.entity.BaseEntity;


/**
 * @Project ChuFangLiuZhuan_PlatForm_Platorm
 * @Package com.sunshine.platform.security.entity
 * @ClassName com.sunshine.platform.security.entity.Dept
 * @TableName SYS_DEPT
 * @Description
 * @JDK version used 1.8.0_111-b14
 * @Author Yuce
 * @Create Date 2017年7月9日
 * @modify By
 * @modify Date
 * @Why&What is modify
 * @Version 1.0
 */
public class Dept extends BaseEntity {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_dept
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = -1054612265;

	/**
	 * 部门名称
	 */
	private String name;

	/**
	 * 更新前的部门名称,用于对比更新时,部门名称是否更改
	 */
	private String oldName;

	/**
	 * 部门编码
	 */
	private String code;

	/**
	 * 备注
	 */
	private String remark;

	/**
	 * 父部门ID
	 */
	private String parentId;

	/**
	 * 父部门名称
	 */
	private String parentName;

	/**
	 * 部门排序号
	 */
	private Integer sortNum;

	/**
	 * @return 部门名称
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            部门名称
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * @return 部门编码
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code
	 *            部门编码
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * @return 备注
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark
	 *            备注
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * @return 父部门ID
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * @param parentId
	 *            父部门ID
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * @return 父部门名称
	 */
	public String getParentName() {
		return parentName;
	}

	/**
	 * @param parentName
	 *            父部门名称
	 */
	public void setParentName(String parentName) {
		this.parentName = parentName == null ? null : parentName.trim();
	}

	/**
	 * @return 部门排序号
	 */
	public Integer getSortNum() {
		return sortNum;
	}

	/**
	 * @param sortNum
	 *            部门排序号
	 */
	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	public String getOldName() {
		return oldName;
	}

	public void setOldName(String oldName) {
		this.oldName = oldName;
	}
}